broadcast_config:
  preprocessing:
    gaussian_blur_kernel: 5
    hsv_green_lower: [30, 35, 35]
    hsv_green_upper: [90, 255, 255]
    morphology_kernel_size: 7
    apply_clahe: true
    
  line_detection:
    threshold: 80
    min_line_length: 60
    
  circle_detection:
    min_radius: 50
    max_radius: 150
    
  camera:
    view_type: "broadcast"
    expected_coverage: 0.85
    typical_height: 25.0
    typical_angle: 35.0
